### ISSUE TITLE
Angular 8rc4: builderHandler is not a function

### ISSUE THREAD

**Issue by bterriervm** [manfredsteyer/ngx-build-plus#100]
After following @Timebutt suggestion in #93, I have the following error:

```
builderHandler is not a function
TypeError: builderHandler is not a function
    at Object.runBuilderHandler (...\node_modules\ngx-build-plus\src\utils\index.js:18:33)
    at buildWebpackBrowserPlus (...\node_modules\ngx-build-plus\src\browser\index.js:7:20)
```

**Comment by bterriervm** [comment]
I had the wrong version of `@angular-devkit/build-angular`.
