### ISSUE TITLE
Angular 8  - Cannot find builder "ngx-build-plus:build"

### ISSUE THREAD

**Issue by MDzyga** [manfredsteyer/ngx-build-plus#104]
Hi, I updated angular to latest version and when I want to build (ng build) or start (ng serve) an application I get an error 

> Cannot find builder "ngx-build-plus:build"

```
Error: Cannot find builder "ngx-build-plus:build".
    at WorkspaceNodeModulesArchitectHost.resolveBuilder (...\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js:45:19)
    at BuildCommand.initialize (...\manage\node_modules\@angular\cli\models\architect-command.js:135:55)
    at async BuildCommand.validateAndRun (...\manage\node_modules\@angular\cli\models\command.js:127:9)
    at async Object.runCommand (...\manage\node_modules\@angular\cli\models\command-runner.js:178:24)
    at async default_1 (...\manage\node_modules\@angular\cli\lib\cli\index.js:32:31)
```

**Packages Versions**
"@angular/animations": "^8.0.0",
"@angular/cdk": "^8.0.0",
"@angular/common": "^8.0.0",
"@angular/compiler": "^8.0.0",
"@angular/core": "^8.0.0",
"@angular/forms": "^8.0.0",
"@angular/material": "^8.0.0",
"@angular/platform-browser": "^8.0.0",
"@angular/platform-browser-dynamic": "^8.0.0",
"@angular/pwa": "^0.800.1",
"@angular/router": "^8.0.0",
"@angular/service-worker": "^8.0.0",
"@angular-devkit/architect": "^0.800.1",
"@angular-devkit/build-angular": "^0.800.1",
"@angular-devkit/build-ng-packagr": "^0.800.1",
"@angular-devkit/core": "^8.0.1",
"typescript": "3.4.1",
"ngx-build-plus": "^8.0.0-rc.3.0.1"

**Comment by thekiba** [comment]
Use `ngx-build-plus:browser` instead of `ngx-build-plus:builder`.

https://github.com/manfredsteyer/ngx-build-plus/issues/93#issuecomment-493890546

**Comment by manfredsteyer** [comment]
Thx, @thekiba for this answer.

Now, we have the final version for 8.0.0 and it contains an update schematic which should change this automatically when upgrading with ng update.

Also, I've re-introduced the old name too to avoid confusions.
