### ISSUE TITLE
Data path ".builders['browser']" should have required property 'class'

### ISSUE THREAD

**Issue by returnvoid** [manfredsteyer/ngx-build-plus#109]
Hi! I can't make it work, using angular cli 7.1.4 and node v10.16.0 && 9.4.0 and I get the same error after running `npm run build` or `ng build`. 

## Error: ##

Schema validation failed with the following errors:
  Data path ".builders['browser']" should have required property 'class'.
Error: Schema validation failed with the following errors:
  Data path ".builders['browser']" should have required property 'class'.
    at MergeMapSubscriber._registry.compile.pipe.operators_1.concatMap.validatorResult [as project] (my-project/node_modules/@angular-devkit/core/src/workspace/workspace.js:215:42)
    at MergeMapSubscriber._tryNext (my-project/node_modules/@angular-devkit/core/node_modules/rxjs/internal/operators/mergeMap.js:69:27)
    at MergeMapSubscriber._next (my-project/node_modules/@angular-devkit/core/node_modules/rxjs/internal/operators/mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (my-project/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:67:18)
    at MergeMapSubscriber.notifyNext (my-project/node_modules/@angular-devkit/core/node_modules/rxjs/internal/operators/mergeMap.js:92:26)
    at InnerSubscriber._next (my-project/node_modules/@angular-devkit/core/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (my-project/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:67:18)
    at MapSubscriber._next (my-project/node_modules/@angular-devkit/core/node_modules/rxjs/internal/operators/map.js:55:26)
    at MapSubscriber.Subscriber.next (my-project/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:67:18)
    at SwitchMapSubscriber.notifyNext (my-project/node_modules/@angular-devkit/core/node_modules/rxjs/internal/operators/switchMap.js:86:26)

## angular.json ##

"architect": {
        "build": {
          "builder": "ngx-build-plus:browser",

## package.json: ##

{
  "name": "project-name",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^7.1.4",
    "@angular/cdk": "^7.3.7",
    "@angular/common": "~7.1.0",
    "@angular/compiler": "~7.1.0",
    "@angular/core": "~7.1.0",
    "@angular/flex-layout": "^7.0.0-beta.24",
    "@angular/forms": "~7.1.0",
    "@angular/material": "^7.3.7",
    "@angular/platform-browser": "~7.1.0",
    "@angular/platform-browser-dynamic": "~7.1.0",
    "@angular/router": "~7.1.0",
    "angular2-moment": "^1.9.0",
    "core-js": "^2.5.4",
    "ng-zorro-antd": "^7.4.1",
    "ngx-build-plus": "^8.1.1",
    "normalize.css": "^8.0.1",
    "rxjs": "^6.3.3",
    "rxjs-compat": "^6.5.1",
    "tslib": "^1.9.0",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.11.0",
    "@angular/cli": "~7.1.4",
    "@angular/compiler-cli": "~7.1.0",
    "@angular/language-service": "~7.1.0",
    "@types/node": "~8.9.4",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.1.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.1.6"
  }
}

thanks

**Comment by knafteN** [comment]
Hi @returnvoid, when you use angular 7 you may also need the corrresponding `ngx-build-plus` version 7. You installed the very latest version, which is 8 and probably meant for angular 8.

So just install the older version: `ng add ngx-build-plus@7` (notice the `@7`)

Hope it helps!

**Comment by khazaddoom** [comment]
> Hi @returnvoid, when you use angular 7 you may also need the corrresponding `ngx-build-plus` version 7. You installed the very latest version, which is 8 and probably meant for angular 8.
> 
> So just install the older version: `ng add ngx-build-plus@7` (notice the `@7`)
> 
> Hope it helps!

This works for me! Hi fi's :)

**Comment by manfredsteyer** [comment]
Yes, exactly. Builders changed a lot with CLI 8
