### ISSUE TITLE
An unhandled exception occurred: Cannot find builder "ngx-build-plus:tslint"

### ISSUE THREAD

**Issue by santosh29** [manfredsteyer/ngx-build-plus#117]
We have upgraded to Angular 8 and running tslint commands. but we are facing  below error 
An unhandled exception occurred: Cannot find builder "ngx-build-plus:tslint"
here is error log

[error] Error: Cannot find builder "ngx-build-plus:tslint".
    at WorkspaceNodeModulesArchitectHost.resolveBuilder (node_modules\@angular\cli\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js:45:19)
    at LintCommand.initialize (node_modules\@angular\cli\models\architect-command.js:72:63)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
[package.txt](https://github.com/manfredsteyer/ngx-build-plus/files/3470910/package.txt)

Refer attached package json

**Comment by santosh29** [comment]
It is solved. We updated the angular.json command to use alternate builder
