### ISSUE TITLE
Could not find the implementation for builder @angular-devkit/build-ng-packagr:build

### ISSUE THREAD

**Issue by tadeussenf** [manfredsteyer/ngx-build-plus#163]
After running `npm run build` in the sample folder I receive this error message:
```> elements-loading@0.0.0 build /home/tadeussenf/Documents/ngx-build-plus/sample
> ng build --extra-webpack-config webpack.externals.js --single-bundle true --prod

Could not find the implementation for builder @angular-devkit/build-ng-packagr:build
Error: Could not find the implementation for builder @angular-devkit/build-ng-packagr:build
    at WorkspaceNodeModulesArchitectHost.resolveBuilder (/home/tadeussenf/Documents/ngx-build-plus/sample/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js:49:19)
    at BuildCommand.initialize (/home/tadeussenf/Documents/ngx-build-plus/sample/node_modules/@angular/cli/models/architect-command.js:72:63)
    at async BuildCommand.validateAndRun (/home/tadeussenf/Documents/ngx-build-plus/sample/node_modules/@angular/cli/models/command.js:127:9)
    at async Object.runCommand (/home/tadeussenf/Documents/ngx-build-plus/sample/node_modules/@angular/cli/models/command-runner.js:178:24)
    at async default_1 (/home/tadeussenf/Documents/ngx-build-plus/sample/node_modules/@angular/cli/lib/cli/index.js:32:31)
```

This is the Angular / Angular CLI version I am using:
```Angular CLI: 8.0.1
Node: 12.14.1
OS: linux x64
Angular: 8.0.0
... animations, common, compiler, compiler-cli, core, elements
... forms, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
@angular-devkit/architect          0.800.1
@angular-devkit/build-angular      0.800.1
@angular-devkit/build-ng-packagr   0.12.4
@angular-devkit/build-optimizer    0.800.1
@angular-devkit/build-webpack      0.800.1
@angular-devkit/core               7.2.2
@angular-devkit/schematics         7.2.2
@angular/cli                       8.0.1
@ngtools/json-schema               1.1.0
@ngtools/webpack                   8.0.1
@schematics/angular                7.2.2
@schematics/update                 0.800.1
ng-packagr                         4.7.1
rxjs                               6.5.2
typescript                         3.4.5
webpack                            4.30.0
```

**Comment by tadeussenf** [comment]
Changing @angular-devkit/build-ng-packagr version in package.json seems to help:

`"@angular-devkit/build-ng-packagr": "~0.800.1",`
