### ISSUE TITLE
Polyfills.ts are not injected

### ISSUE THREAD

**Issue by CarlosTenorio** [manfredsteyer/ngx-build-plus#169]
The _src/polyfills_.ts are not injected when compile the app. I'm not sure if I need some special flag to enable it.

My script to execute the build is:
`ng build --extra-webpack-config webpack.externals.js --prod --project myProject --single-bundle --output-hashing none`

Version: 9.0.6

**Comment by nandowalter** [comment]
If I try the same config as you, but with --output-hashing all, the build gives me an error:

ERROR in polyfills-es5.09e38d40b873ec787887.js from Terser
Invalid syntax: .09e38d40b873ec787887 [polyfills-es5.09e38d40b873ec787887.js:1,13]
    at ee (/Users/fwalter/dev/brg-ui-cruises/node_modules/@angular-devkit/build-angular/node_modules/terser/dist/bundle.min.js:1:19391)
    at m (/Users/fwalter/dev/brg-ui-cruises/node_modules/@angular-devkit/build-angular/node_modules/terser/dist/bundle.min.js:1:20707)
    at E (/Users/fwalter/dev/brg-ui-cruises/node_modules/@angular-devkit/build-angular/node_modules/terser/dist/bundle.min.js:1:21439)
    at Object.L [as input] (/Users/fwalter/dev/brg-ui-cruises/node_modules/@angular-devkit/build-angular/node_modules/terser/dist/bundle.min.js:1:25643)
    at a (/Users/fwalter/dev/brg-ui-cruises/node_modules/@angular-devkit/build-angular/node_modules/terser/dist/bundle.min.js:1:27629)
    at s (/Users/fwalter/dev/brg-ui-cruises/node_modules/@angular-devkit/build-angular/node_modules/terser/dist/bundle.min.js:1:27683)
    at B (/Users/fwalter/dev/brg-ui-cruises/node_modules/@angular-devkit/build-angular/node_modules/terser/dist/bundle.min.js:1:39676)
    at G (/Users/fwalter/dev/brg-ui-cruises/node_modules/@angular-devkit/build-angular/node_modules/terser/dist/bundle.min.js:1:42181)
    at De (/Users/fwalter/dev/brg-ui-cruises/node_modules/@angular-devkit/build-angular/node_modules/terser/dist/bundle.min.js:1:47765)
    at ve (/Users/fwalter/dev/brg-ui-cruises/node_modules/@angular-devkit/build-angular/node_modules/terser/dist/bundle.min.js:1:48491)
