### ISSUE TITLE
AngularCompilerPlugin is undefined in Angular V12

### ISSUE THREAD

**Issue by Ajyress** [manfredsteyer/ngx-build-plus#298]
Hi,

I get the following error when trying to add a custom transformer to AngularCompilerPlugin. 

> An unhandled exception occurred: Cannot read property '_transformers' of undefined
See "C:\Users\David\AppData\Local\Temp\ng-mgpXz3\angular-errors.log" for further details.

Here is the content of angular-errors.log:

> [error] TypeError: Cannot read property '_transformers' of undefined
    at Object.config (G:\experiments\testAngularCompilerPlugin\dist\out-tsc\plugins.js:31:77)
    at transforms.<computed> (G:\experiments\testAngularCompilerPlugin\node_modules\ngx-build-plus\src\utils\index.js:60:29)
    at initialize (G:\experiments\testAngularCompilerPlugin\node_modules\@angular-devkit\build-angular\src\browser\index.js:83:35)
    at async SwitchMapSubscriber.project (G:\experiments\testAngularCompilerPlugin\node_modules\@angular-devkit\build-angular\src\browser\index.js:114:17)

**Steps to reproduce the bug**

1.  Create a new Angular V12 project:
`ng new myProjectName`

2.  Add ngx-build-plus to the project
`ng add ngx-build-plus`

3.  Inside the project folder, create a plugins.ts file with following content:
```
export default {

    pre() {},
  
    config(config: any) {

        const plugins = config.plugins;
        const modernPlugins = [...plugins];
        const acpIndex = plugins.findIndex((p :any) => p.constructor.name === 'AngularCompilerPlugin');
        const angularCompilerPlugin = plugins[acpIndex];
  
        angularCompilerPlugin._transformers = [...angularCompilerPlugin._transformers];
  
        return config;

    },
  
    post() {},
  
 };
```

4. Compile plugins
`tsc --skipLibCheck --module umd`

5. Build Angular project with plugins
`ng build --plugin ~dist/out-tsc/plugins.js`

My guess is that AngularCompilerPlugin is not accessible anymore with ivy compiler.
Do you know any workaround?

**Comment by morrys** [comment]
hi @Ajyress,
I found a workaround and I recommend reading this article of mine:
https://medium.com/@morrys/custom-typescript-transformers-with-angular-for-angular-11-12-and-13-40cbdc9cca7b
and an example of a transformation made by me compatible with angular v11, v12 and v13 👍 
https://github.com/morrys/relay-angular/blob/master/packages/relay-angular-plugin/src/index.ts

Let me know what do you think 💯
