### ISSUE TITLE
Error: ENOENT: no such file or directory, scandir in Angular V13

### ISSUE THREAD

**Issue by RoopanV** [manfredsteyer/ngx-build-plus#313]
In angular V13, with extractLicenses true facing the above issue. But building angular native bundler the above issue is not coming.

[error] HookWebpackError: ENOENT: no such file or directory, scandir
    at makeWebpackError (/Users/Desktop/illusion/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/HookWebpackError.js:48:9)
    at /Users/Desktop/illusion/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compilation.js:3055:12
    at eval (eval at create (/Users/Desktop/illusion/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:31:1)
    at fn (/Users/Desktop/illusion/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compilation.js:478:17)
    at _next5 (eval at create (/Users/Desktop/illusion/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:28:1)
    at eval (eval at create (/Users/Desktop/illusion/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:46:1)
    at fn (/Users/Desktop/illusion/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compilation.js:490:9)
    at _next4 (eval at create (/Users/Desktop/illusion/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:41:1)
    at eval (eval at create (/Users/Desktop/illusion/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:60:1)
    at runMicrotasks (<anonymous>)

Even though feels the issue with some other plugin but the issue is not appearing in angular native builder make me to feels like something to do with ngx build plus.

Thanks in Advance.

**Comment by aaryavrate** [comment]
How did you solve this?

**Comment by EmirhanAksoy** [comment]
same here

**Comment by minijus** [comment]
Workaround provided by @Coly010 on nrwl/nx migth be applicable here as well. See comment: https://github.com/nrwl/nx/issues/12317#issuecomment-1275967489
