### ISSUE TITLE
Can't Use MiniCssExtractPlugin in 12.2.x  works in 12.1.x

### ISSUE THREAD

**Issue by nawlbergs** [manfredsteyer/ngx-build-plus#322]
I'm trying to move from angularJs to angular 12... my controllers would often import less files... 
Heres my export with 12.1 (it works):

```javascript
// wepack.partial.js
module.exports = {
  module: {
    rules: [
      {
        test: /\.(less|css)$/,
        include:[
          /common/
        ],
        use: [
          MiniCssExtractPlugin.loader,
          { loader: 'css-loader', options: { sourceMap: true }},
          {
            loader: 'postcss-loader',
            options: {
              sourceMap: true,
              postcssOptions: {
                map: true,
                plugins: [
                  require('autoprefixer')
                ]
              },
            },
          },
          {
            loader:'less-loader',
            options: { sourceMap: true }}
        ],
      },
    ],
  }
};
```

If i upgrade my angular versions from `12.1.4` to `12.2.15 (latest for v12)` I get....

```bash
../files/.../styles.less - Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
Error: You forgot to add 'mini-css-extract-plugin' plugin (i.e. `{ plugins: [new MiniCssExtractPlugin()] }`), please read https://github.com/webpack-contrib/mini-css-extract-plugin#getting-started
    at Object.pitch (C:\Users\alber\sites\af-client\public\portal\node_modules\mini-css-extract-plugin\dist\loader.js:51:14)
```
So naturally I...
```javascript
// wepack.partial.js
module.exports = {
  plugins: [ new MiniCssExtractPlugin() ], // <----- added this
  module: {
    rules: [ 
      ...
```
But then i get
```bash
 Generating browser application bundles (phase: setup)...An unhandled exception occurred: ObjectMiddleware.register: serializer for mini-css-extract-plugin/dist/CssModule/null is already registered
[error] Error: ObjectMiddleware.register: serializer for mini-css-extract-plugin/dist/CssModule/null is already registered
    at Object.register (C:\Users\alber\sites\af-client\public\portal\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\serialization\ObjectMiddleware.js:182:10)
    at Function.getCssModule (C:\Users\alber\sites\af-client\public\portal\node_modules\mini-css-extract-plugin\dist\index.js:182:34)
    at MiniCssExtractPlugin.apply (C:\Users\alber\sites\af-client\public\portal\node_modules\mini-css-extract-plugin\dist\index.js:389:44)
    at createCompiler (C:\Users\alber\sites\af-client\public\portal\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\webpack.js:74:12)
    at create (C:\Users\alber\sites\af-client\public\portal\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\webpack.js:127:16)
    at webpack (C:\Users\alber\sites\af-client\public\portal\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\webpack.js:151:32)
    at Object.f [as webpackFactory] (C:\Users\alber\sites\af-client\public\portal\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\index.js:55:16)
    at createWebpack (C:\Users\alber\sites\af-client\public\portal\node_modules\@angular-devkit\build-angular\node_modules\@angular-devkit\build-webpack\src\webpack-dev-server\index.js:43:36)
    at Object.runWebpackDevServer (C:\Users\alber\sites\af-client\public\portal\node_modules\@angular-devkit\build-angular\node_modules\@angular-devkit\build-webpack\src\webpack-dev-server\index.js:73:12)
    at SwitchMapSubscriber.project (C:\Users\alber\sites\af-client\public\portal\node_modules\@angular-devkit\build-angular\src\dev-server\index.js:247:32)
    at SwitchMapSubscriber._next (C:\Users\alber\sites\af-client\public\portal\node_modules\rxjs\internal\operators\switchMap.js:47:27)
    at SwitchMapSubscriber.Subscriber.next (C:\Users\alber\sites\af-client\public\portal\node_modules\rxjs\internal\Subscriber.js:66:18)
    at C:\Users\alber\sites\af-client\public\portal\node_modules\rxjs\internal\util\subscribeToPromise.js:7:24
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

```

**Comment by axlroseart** [comment]
must add this config in ‘angular.json’:
`"customWebpackConfig": {
        "path": "your-custom-webpack.config.js",
+      **"replaceDuplicatePlugins": true**
 }`
