### ISSUE TITLE
Cannot find module version 7.6.0

### ISSUE THREAD

**Issue by chukwu** [manfredsteyer/ngx-build-plus#62]
**I saw a similar issue on closed issues list. Nothing was mentioned on how to fix it and what the cause was.**

```
Cannot find module '/Users/kalebr/dev/fileManager/angularElements/node_modules/ngx-build-plus/src/plus'
Error: Cannot find module '/Users/kalebr/dev/fileManager/angularElements/node_modules/ngx-build-plus/src/plus'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Architect.getBuilder (/Users/kalebr/dev/fileManager/angularElements/node_modules/@angular-devkit/architect/src/architect.js:189:35)
    at MapSubscriber.getBuilderDescription.pipe.operators_1.map [as project] (/Users/kalebr/dev/fileManager/angularElements/node_modules/@angular-devkit/architect/src/architect.js:121:332)
```

**Comment by chukwu** [comment]
Strange!!!
I uninstalled it and reinstalled. Suddenly Fixed!!!

**Comment by manfredsteyer** [comment]
Thx for the info. Glad that it works now.
